//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public double Salario { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int idCargo { get; set; }
    
        public virtual Cargos Cargos { get; set; }
    }
}
